apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spring-boot-chart.fullname" . }}
  labels:
    helm.sh/chart: {{ include "spring-boot-chart.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.selector: {{ include "spring-boot-chart.fullname" . }}
    {{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
    {{- end }}
spec:

  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.selector: {{ include "spring-boot-chart.fullname" . }}
  template:
    metadata:
      annotations:
{{ toYaml .Values.deployment.annotations | indent 8 }}
      labels:
        app.selector: {{ include "spring-boot-chart.fullname" . }}
        {{- if .Values.labels }}
{{ toYaml .Values.labels | indent 8 }}
        {{- end }}
    spec:
      {{- if .Values.rbac.create }}
      serviceAccountName: {{ include "spring-boot-chart.fullname" . }}
      {{- end }}
      containers:
        {{- range $index, $container := .Values.deployment.containers }}
        # Container {{ $index }} - {{ $container.name }}
        - name: {{ $container.name }}
          image: "{{ $container.image.repository }}:{{ $container.image.tag }}"
          imagePullPolicy: {{ $container.image.pullPolicy }}
          {{- if (gt (len $container.env.vars) 0) }}
          env:
          # env vars
{{ toYaml $container.env.vars | indent 10 }}
          {{- end }}
          #ports:
          {{- if $container.ports }}
          ports:
          {{- range $index, $item := $container.ports }}
          # Port {{ $index }}
          - containerPort: {{ $item.containerPort }}
            protocol: {{ $item.protocol }}
            name: {{ $item.name }}
          {{- end }}
          {{- end }}
          # END: ports
          {{- if $container.livenessProbe }}
          livenessProbe:
{{ toYaml $container.livenessProbe | indent 12 }}
          {{- end }}
          {{- if $container.readinessProbe }}
          readinessProbe:
{{ toYaml $container.readinessProbe | indent 12 }}
          {{- end }}
          resources:
            {{- toYaml $container.resources | nindent 12 }}

          securityContext:
            {{- toYaml $container.securityContext | nindent 12 }}
        {{- end }}


      {{- if .Values.deployment.imagePullSecrets }}
      imagePullSecrets:      
      {{- range .Values.deployment.imagePullSecrets }}
      - name: {{ . }}
      {{- end }}
      {{- end }}

      {{- with .Values.volumes }}
      # Volumes
      volumes:
{{- toYaml . | nindent 8 }}
      {{- end }}
