{{- if .Values.hpa.enabled -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "spring-boot-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
{{ toYaml .Values.hpa.spec | indent 2 }}
{{- end }}
