{{- if .Values.ingress.enabled -}}
{{- $fullName := include "spring-boot-chart.fullname" . -}}
{{- $ingressPaths := .Values.ingress.paths -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    helm.sh/chart: {{ include "spring-boot-chart.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - http:
        paths:
	{{- range $ingressPaths }}
          - pathType: {{ .pathType }}
            path: {{ .path }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: {{ .servicePort }}
  {{- end }}
{{- end }}