{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "spring-boot-chart.fullname" . }}
  labels:
    helm.sh/chart: {{ include "spring-boot-chart.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.selector: {{ include "spring-boot-chart.fullname" . }}
    {{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
    {{- end }}
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources:
      - secrets
      - pods
      - services
      - endpoints
    verbs:
      - get
      - list
      - watch
  - apiGroups: [ "", "extensions", "apps" ]
    resources:
      - configmaps
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
{{- end }}