# Only create a service if the Deployment has exposed a port
{{- $containerHasExposedPorts := false -}}
{{- range $index, $container := .Values.deployment.containers }}
  {{- range $index, $item := $container.ports }}
    {{ $containerHasExposedPorts = true }}
  {{- end }}
{{- end }}

{{- if  $containerHasExposedPorts }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-boot-chart.fullname" . }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    helm.sh/chart: {{ include "spring-boot-chart.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $index, $container := .Values.deployment.containers }}
      {{- range $index, $item := $container.ports }}
    - port: {{ $item.servicePort }}
      targetPort: {{ $item.name }}
      protocol: {{ $item.protocol }}
      name: {{ $item.name }}
      {{- end }}
    {{- end }}
  selector:
    app.selector: {{ include "spring-boot-chart.fullname" . }}
{{- end }}