{{- if .Values.ingress.enabled -}}
{{- $fullName := include "spring-boot-chart.fullname" . -}}
{{- $ingressPaths := .Values.ingress.paths -}}
{{- $ingressHosts := .Values.ingress.hosts -}}
{{- $ingressTlsHosts := .Values.ingress.tlshosts -}}


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    helm.sh/chart: {{ include "spring-boot-chart.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.selector: {{ include "spring-boot-chart.fullname" . }}
    app.kubernetes.io/name: {{ include "spring-boot-chart.fullname" . }}
    app.kubernetes.io/version: {{ .Values.version }}
    app: {{ include "spring-boot-chart.fullname" . }}
    version: {{ .Values.version }}
    {{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
    {{- end }}
{{- with .Values.ingress.annotations }}
  annotations:
{{- toYaml . | nindent 4 }}
{{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- if .Values.ingress.tlsenabled }}
  tls:
    - hosts:
  {{- range $ingressHosts }}
      - {{ . | quote }}
  {{- end }}
  {{- range $ingressTlsHosts }}
      - {{ . | quote }}
  {{- end }}
      secretName: {{ printf "%s-cert" $fullName }}
  {{- end }}
  rules:
    {{- range $ingressHosts }}
    - host: {{ . | quote }}
      http:
        paths:
	{{- range $ingressPaths }}
          - pathType: {{ .pathType }}
            path: {{ .path }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: {{ .servicePort }}
    {{- end }}
    {{- end }}
{{- end }}