{{- if .Values.rbac.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "spring-boot-chart.fullname" . }}
  labels:
    helm.sh/chart: {{ include "spring-boot-chart.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.selector: {{ include "spring-boot-chart.fullname" . }}
    app.kubernetes.io/name: {{ include "spring-boot-chart.fullname" . }}
    app.kubernetes.io/version: {{ .Values.version }}
    app: {{ include "spring-boot-chart.fullname" . }}
    version: {{ .Values.version }}
roleRef:
    kind: Role
    name: {{ include "spring-boot-chart.fullname" . }}
    apiGroup: rbac.authorization.k8s.io
subjects:
    - kind: ServiceAccount
      name: {{ include "spring-boot-chart.fullname" . }}
      namespace: {{ .Release.Namespace }}
{{- end }}