{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spring-boot-chart.fullname" . }}
  labels:
    helm.sh/chart: {{ include "spring-boot-chart.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.selector: {{ include "spring-boot-chart.fullname" . }}
    app.kubernetes.io/name: {{ include "spring-boot-chart.fullname" . }}
    app.kubernetes.io/version: {{ .Values.version }}
    {{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
    {{- end }}
{{- end }}
